import Head from "next/head";
import Image from "next/image";
import React from "react";

export default function Home() {
    const [torn, setTorn] = React.useState(false);

    const tearWallpaper = (event) => {
        setTorn(true);
    };

    return (
        <div>
            <Head>
                <title>The Yellow Wallpaper</title>
            </Head>
            <div
                className={`min-h-screen bg-cover ${
                    torn ? "bg-wallpaper_torn" : "bg-wallpaper"
                }`}
            >
                <div className="container mx-auto flex items-center justify-center py-8">
                    <div className="bg-black/20 p-4 rounded-full">
                        <button
                            className="text-2xl font-semibold px-8 bg-yellow-500 text-black rounded shadow-md shadow-yellow-600 hover:bg-yellow-400 active:bg-yellow-600"
                            onClick={tearWallpaper}
                        >
                            Tear
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
    //     <div className={styles.container}>
    //         <Head>
    //             <title>Create Next App</title>
    //             <meta
    //                 name="description"
    //                 content="Generated by create next app"
    //             />
    //             <link rel="icon" href="/favicon.ico" />
    //         </Head>

    //         <main className={styles.main}>
    //             <h1 className={styles.title}>
    //                 Welcome to <a href="https://nextjs.org">Next.js!</a>
    //             </h1>

    //             <p className={styles.description}>
    //                 Get started by editing{" "}
    //                 <code className={styles.code}>pages/index.js</code>
    //             </p>

    //             <div className={styles.grid}>
    //                 <a href="https://nextjs.org/docs" className={styles.card}>
    //                     <h2>Documentation &rarr;</h2>
    //                     <p>
    //                         Find in-depth information about Next.js features and
    //                         API.
    //                     </p>
    //                 </a>

    //                 <a href="https://nextjs.org/learn" className={styles.card}>
    //                     <h2>Learn &rarr;</h2>
    //                     <p>
    //                         Learn about Next.js in an interactive course with
    //                         quizzes!
    //                     </p>
    //                 </a>

    //                 <a
    //                     href="https://github.com/vercel/next.js/tree/canary/examples"
    //                     className={styles.card}
    //                 >
    //                     <h2>Examples &rarr;</h2>
    //                     <p>
    //                         Discover and deploy boilerplate example Next.js
    //                         projects.
    //                     </p>
    //                 </a>

    //                 <a
    //                     href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //                     className={styles.card}
    //                 >
    //                     <h2>Deploy &rarr;</h2>
    //                     <p>
    //                         Instantly deploy your Next.js site to a public URL
    //                         with Vercel.
    //                     </p>
    //                 </a>
    //             </div>
    //         </main>

    //         <footer className={styles.footer}>
    //             <a
    //                 href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //                 target="_blank"
    //                 rel="noopener noreferrer"
    //             >
    //                 Powered by{" "}
    //                 <span className={styles.logo}>
    //                     <Image
    //                         src="/vercel.svg"
    //                         alt="Vercel Logo"
    //                         width={72}
    //                         height={16}
    //                     />
    //                 </span>
    //             </a>
    //         </footer>
    //     </div>
    // );
}
